// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/AllPaste/paste/config"
	"github.com/AllPaste/paste/internal/app"
	"github.com/AllPaste/paste/internal/data/repository"
	"github.com/AllPaste/paste/internal/driver"
	"github.com/AllPaste/paste/internal/service"
	"github.com/AllPaste/paste/pkg/log"
)

// Injectors from wire.go:

// InitializeEvent 声明injector的函数签名
func server(c *config.Config, logger *log.Logger) (*app.Server, func(), error) {
	client, cleanup, err := driver.NewDriver(c)
	if err != nil {
		return nil, nil, err
	}
	paste := repository.NewPasteRepo(client, logger)
	pasteService := service.NewPasteService(paste, logger)
	appServer := app.NewServer(c, logger, pasteService)
	return appServer, func() {
		cleanup()
	}, nil
}
