// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// PastesColumns holds the columns for the "pastes" table.
	PastesColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "content", Type: field.TypeString, Size: 2147483647},
		{Name: "creator", Type: field.TypeString},
	}
	// PastesTable holds the schema information for the "pastes" table.
	PastesTable = &schema.Table{
		Name:       "pastes",
		Columns:    PastesColumns,
		PrimaryKey: []*schema.Column{PastesColumns[0]},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		PastesTable,
	}
)

func init() {
}
