// Code generated by ent, DO NOT EDIT.

package paste

const (
	// Label holds the string label denoting the paste type in the database.
	Label = "paste"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldContent holds the string denoting the content field in the database.
	FieldContent = "content"
	// FieldCreator holds the string denoting the creator field in the database.
	FieldCreator = "creator"
	// Table holds the table name of the paste in the database.
	Table = "pastes"
)

// Columns holds all SQL columns for paste fields.
var Columns = []string{
	FieldID,
	FieldContent,
	FieldCreator,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}
